server:
  port: 8000
spring:
  profiles:
    active: dev
## myBatisPlus
mybatis-plus:
  type-aliases-package: com.wxblog.core.bean
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

